# Generated by Django 5.1.5 on 2025-01-24 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='events',
            field=models.ManyToManyField(to='events.event'),
        ),
    ]
