# Generated by Django 5.1.5 on 2025-01-25 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_attendance_event_attendees'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['start_date']},
        ),
        migrations.AlterField(
            model_name='calendar',
            name='events',
            field=models.ManyToManyField(blank=True, to='events.event'),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='members',
            field=models.ManyToManyField(blank=True, to='events.member'),
        ),
    ]
